[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224
    Tag           app.logs

## エラー判定用フィルタ
# - rewrite_tag を使い、ログの中に [ERROR] が含まれるものを別タグにコピーする
# - 「Rule」の第一引数はマッチさせるキー名(例: "message")
# - 第二引数が正規表現
# - 第三引数がマッチしたときの付与タグ名
# - 第四引数を "true" にすることで、マッチしたログのコピーを生成(元タグには影響なし)
[FILTER]
    Name                rewrite_tag
    Match               app.logs
    Rule                log ^.*\[ERROR\].*$ app.error.logs true
    Emitter_Name        app.error.logs
    Emitter_Storage.type  memory

## エラーログ専用: CloudWatch Logs に出力 (app.error.logs)
[OUTPUT]
    Name                cloudwatch_logs
    Match               app.error.logs
    region              ap-northeast-1
    log_group_name      poc-log-202503-errors
    log_stream_prefix   express-app/

## すべてのログ: Kinesis Firehose に出力 (app.logs)
[OUTPUT]
    Name                kinesis_firehose
    Match               app.logs
    region              ap-northeast-1
    delivery_stream     poc-log-202503-stream
    auto_retry_requests true
